//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyExtractorClient.MoneyExtractorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractRequest", Namespace="http://schemas.datacontract.org/2004/07/MoneyExtractorService.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataRequest))]
    public partial class AbstractRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDataRequest", Namespace="http://schemas.datacontract.org/2004/07/MoneyExtractorService.Entities")]
    [System.SerializableAttribute()]
    public partial class PaymentDataRequest : MoneyExtractorClient.MoneyExtractorServiceReference.AbstractRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PaidAmountInCentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductAmountInCentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PaidAmountInCents {
            get {
                return this.PaidAmountInCentsField;
            }
            set {
                if ((this.PaidAmountInCentsField.Equals(value) != true)) {
                    this.PaidAmountInCentsField = value;
                    this.RaisePropertyChanged("PaidAmountInCents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductAmountInCents {
            get {
                return this.ProductAmountInCentsField;
            }
            set {
                if ((this.ProductAmountInCentsField.Equals(value) != true)) {
                    this.ProductAmountInCentsField = value;
                    this.RaisePropertyChanged("ProductAmountInCents");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractResponse", Namespace="http://schemas.datacontract.org/2004/07/MoneyExtractorService.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataResponse))]
    public partial class AbstractResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDataResponse", Namespace="http://schemas.datacontract.org/2004/07/MoneyExtractorService.Entities")]
    [System.SerializableAttribute()]
    public partial class PaymentDataResponse : MoneyExtractorClient.MoneyExtractorServiceReference.AbstractResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalAmountInCentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MoneyExtractorClient.MoneyExtractorServiceReference.ChangeData changeDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalAmountInCents {
            get {
                return this.TotalAmountInCentsField;
            }
            set {
                if ((this.TotalAmountInCentsField.Equals(value) != true)) {
                    this.TotalAmountInCentsField = value;
                    this.RaisePropertyChanged("TotalAmountInCents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MoneyExtractorClient.MoneyExtractorServiceReference.ChangeData changeData {
            get {
                return this.changeDataField;
            }
            set {
                if ((object.ReferenceEquals(this.changeDataField, value) != true)) {
                    this.changeDataField = value;
                    this.RaisePropertyChanged("changeData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeData", Namespace="http://schemas.datacontract.org/2004/07/MoneyExtractorService.Entities")]
    [System.SerializableAttribute()]
    public partial class ChangeData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<MoneyExtractorClient.MoneyExtractorServiceReference.ChangeType, System.Collections.Generic.Dictionary<long, long>> ChangeTotalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<MoneyExtractorClient.MoneyExtractorServiceReference.ChangeType, System.Collections.Generic.Dictionary<long, long>> ChangeTotalResult {
            get {
                return this.ChangeTotalResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTotalResultField, value) != true)) {
                    this.ChangeTotalResultField = value;
                    this.RaisePropertyChanged("ChangeTotalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeType", Namespace="http://schemas.datacontract.org/2004/07/MoneyExtractorService.Entities")]
    public enum ChangeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bill = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Coin = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoneyExtractorServiceReference.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/SellProduct", ReplyAction="http://tempuri.org/IClienteService/SellProductResponse")]
        MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataResponse SellProduct(MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataRequest paymentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/SellProduct", ReplyAction="http://tempuri.org/IClienteService/SellProductResponse")]
        System.Threading.Tasks.Task<MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataResponse> SellProductAsync(MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataRequest paymentData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : MoneyExtractorClient.MoneyExtractorServiceReference.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<MoneyExtractorClient.MoneyExtractorServiceReference.IClienteService>, MoneyExtractorClient.MoneyExtractorServiceReference.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataResponse SellProduct(MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataRequest paymentData) {
            return base.Channel.SellProduct(paymentData);
        }
        
        public System.Threading.Tasks.Task<MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataResponse> SellProductAsync(MoneyExtractorClient.MoneyExtractorServiceReference.PaymentDataRequest paymentData) {
            return base.Channel.SellProductAsync(paymentData);
        }
    }
}
